### ISSUE TITLE
Unable to launch iblviewer

### ISSUE THREAD

**Issue by cmlangdon** [int-brain-lab/iblviewer#11]
I get the following error when trying to launch the iblviewer:

(myenv) scidi3:~ langdon$ iblviewer
Traceback (most recent call last):
  File "/Users/langdon/opt/anaconda3/envs/myenv/bin/iblviewer", line 5, in <module>
    from iblviewer.launcher import main
  File "/Users/langdon/opt/anaconda3/envs/myenv/lib/python3.8/site-packages/iblviewer/__init__.py", line 2, in <module>
    import iblviewer.mouse_brain
  File "/Users/langdon/opt/anaconda3/envs/myenv/lib/python3.8/site-packages/iblviewer/mouse_brain.py", line 36, in <module>
    class AllenAtlasExt(ibllib.atlas.AllenAtlas):
TypeError: lru_cache() missing required argument 'cache_info_type' (pos 4)

Steps to reproduce:
1) conda create -n myenv python=3.8
2) conda activate myenv
3) pip install ibllib
4) pip install git+https://github.com/int-brain-lab/iblviewer.git
5) iblviewer

**Comment by nantille** [comment]
You're right. The issue comes from `ibllib`, not `iblviewer`. A `@lru_cache` decorator that was apparently added to `ibllib.atlas.AllenAtlas` (@oliche), so this is breaking iblviewer that extends this class with `class AllenAtlasExt(ibllib.atlas.AllenAtlas)`. Please ask him to have a look if he can remove that.

**Comment by berkgercek** [comment]
@cmlangdon A temporary workaround is to check out the commits from before the lru_cache decorator was added, which was in mid december, or to just comment out that line in your ibllib/ibllib/atlas.py file so that the AllenAtlas is undecorated

**Comment by oliche** [comment]
We'll remove this and cache the methods only instead. This should allow us to subclass AllenAtlas in this codebase.

**Comment by nantille** [comment]
Thanks, closing this then.
