### ISSUE TITLE
Index out of bounds error when trying to init viewer

### ISSUE THREAD

**Issue by berkgercek** [int-brain-lab/iblviewer#12]
I'm attempting to run the example scripts, and have created an environment on my local machine that has everything the viewer needs. However I get the following error when attempting to load any atlas:

```
Traceback (most recent call last):
  File "/home/berk/mambaforge/envs/iblviewer/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/home/berk/mambaforge/envs/iblviewer/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/home/berk/Documents/iblviewer/iblviewer/qt_application.py", line 139, in _initialize_viewer
    self.viewer.initialize(plot=self.plot, dark_mode=self.dark_mode, **self.kwargs)
  File "/home/berk/Documents/iblviewer/iblviewer/mouse_brain.py", line 444, in initialize
    self.ibl_model.get_atlas_model(mapping)
  File "/home/berk/Documents/iblviewer/iblviewer/mouse_brain.py", line 191, in get_atlas_model
    self.atlas_volume.data = self.get_mapped_volume(self.atlas.label, atlas_mapping)
  File "/home/berk/Documents/iblviewer/iblviewer/mouse_brain.py", line 350, in get_mapped_volume
    volume_data = self.atlas.regions.mappings[map_id][volume]
IndexError: index 312782632 is out of bounds for axis 0 with size 2655
```
Have tried reinstalling ibllib, the viewer itself, and a new environment with no solution. Not sure how this could happen, as the error occurs only on my home machine while the work machine (on ubuntu with the exact same environments I think) works fine.

**Comment by nantille** [comment]
Hi Berk, I've tested installing iblviewer on new conda envs, one with python 3.8 and another with python 3.9. Both work for me. However, in the error message, it seems that you're running iblviewer from a cloned repo, not from a pip install. 

When working with IBL data, the viewer loads the Allen atlas, computes the mapping and stores it locally in the flatiron cache (defined in the related IBL config file). If you have multiple iblviewer installed, they all rely on the same cache. Could you try to clear the cache and run the viewer again? It will take some time rebuilding the cache when you load it for the first time.

**Comment by berkgercek** [comment]
Yep this was indeed the issue, had to dig around to find the files and delete them but it worked afterwards.
