### ISSUE TITLE
Accessing current time series value in qt viewer not working

### ISSUE THREAD

**Issue by berkgercek** [int-brain-lab/iblviewer#14]
I'm trying to use the `viewer.get_time_series_info` function and/or the `viewer.last_time_series_value` attribute to adjust how my custom functions in the volume mapping examples access data. However the issues is that for values of the time series beyond 1, the returned value is always `None`...

Suggestions on what to do? For reference, here is how I'm building the time series:

```
for basenum in range(self.nbases):
    scalars_map = self.get_scalars_map(viewer, str(basenum))
    viewer.select(-1)
    viewer.assign_scalars(scalars_map, [self.min_value, self.max_value],
                          self.color_map)
```
assume get_scalars_map works correctly, and the added argument is just so it knows what part of the internal dataframe holding my data it wants to access.

**Comment by nantille** [comment]
`get_time_series_info()` provides you with values that represent the state of your series, not the actual data in the time series. So if you use this method, you will know that if you have of time series of 10 data sets and the selected one is 4, you will get 4 and 10 using this method. However, the method relies on either a current valid selection or a valid given target, in your case that's a volume.

If elsewhere in your code you change the selection or add a new object that is selected by default, then calling `get_time_series_info()` will try to fetch info from that other object.

Could you `print(viewer.model.selection.name)` in your code before where you want to call `get_time_series_info()`?
If `name` is not accessible, it means that `viewer.model.selection` is None or invalid. If you see `Allen Mouse CCF v3 Atlas volume` in the console then your selection is valid and `get_time_series()` should work and I'll investigate why.

If your selection is invalid, you may also select the right object with its name with `viewer.select('Allen Mouse CCF v3 Atlas volume')` or with the volume object itself with `viewer.select(viewer.atlas_controller.actor)`, assuming you're using the Allen atlas.
