### ISSUE TITLE
Add third-party volume

### ISSUE THREAD

**Issue by oliche** [int-brain-lab/iblviewer#2]
I want to add a volume and overlay to the current Atlas. The volume is arbitrary and completely independent of brain regions.
(it is a spatial coverage volume).
The volume is in the same coordinate framework as the atlas (the same dimensions / orientations).

In the future, it could be anything (gene expression, spatial firing rates etc..).

(see the coverage.py example here: https://github.com/int-brain-lab/iblviewer/blob/f42154dbe8d00c558bde06304ca06db37613a109/examples/coverage.py#L1)

**Comment by nantille** [comment]
Multiple volumes are already supported by design in the model and your example is almost how one adds such a data set. The viewer needs more functionalities with respect to multiple data sets (not just volumes).

After the next release this week, I'll work on adding such functionalities. Thanks!

**Comment by nantille** [comment]
@oliche The version 2 of the viewer now supports any kind of data set supported by VTK. Mixing volumes, surface meshes and points/lines is integrated. You will find your adapted coverage.py in the example as [ibl_brain_coverage.py](https://github.com/int-brain-lab/iblviewer/blob/main/examples/neuroscience/ibl_brain_coverage.py).
