### ISSUE TITLE
Error with updating iblviewer

### ISSUE THREAD

**Issue by Marsataheri** [int-brain-lab/iblviewer#7]
I am not able to update iblviewer; below is the error I get and a screenshot of it.

`(iblenv) mt@Marsas-MacBook-Pro int-brain-lab % pip install -U git+https://github.com/int-brain-lab/iblviewer.git
Collecting git+https://github.com/int-brain-lab/iblviewer.git
  Cloning https://github.com/int-brain-lab/iblviewer.git to /private/var/folders/4g/bsv4mh852jsdhscq8svz94pw0000gn/T/pip-req-build-p3_8zncx
  Running command git clone -q https://github.com/int-brain-lab/iblviewer.git /private/var/folders/4g/bsv4mh852jsdhscq8svz94pw0000gn/T/pip-req-build-p3_8zncx
  Resolved https://github.com/int-brain-lab/iblviewer.git to commit 5a1b811372ef91d875b073dea0c755ea1e897671
    ERROR: Command errored out with exit status 1:
     command: /Users/mt/opt/anaconda3/envs/iblenv/bin/python3.9 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/4g/bsv4mh852jsdhscq8svz94pw0000gn/T/pip-req-build-p3_8zncx/setup.py'"'"'; __file__='"'"'/private/var/folders/4g/bsv4mh852jsdhscq8svz94pw0000gn/T/pip-req-build-p3_8zncx/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/4g/bsv4mh852jsdhscq8svz94pw0000gn/T/pip-pip-egg-info-4l06dns8
         cwd: /private/var/folders/4g/bsv4mh852jsdhscq8svz94pw0000gn/T/pip-req-build-p3_8zncx/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/4g/bsv4mh852jsdhscq8svz94pw0000gn/T/pip-req-build-p3_8zncx/setup.py", line 2, in <module>
        import iblviewer.launcher
      File "/private/var/folders/4g/bsv4mh852jsdhscq8svz94pw0000gn/T/pip-req-build-p3_8zncx/iblviewer/__init__.py", line 3, in <module>
        from iblviewer.qt_application import *
      File "/private/var/folders/4g/bsv4mh852jsdhscq8svz94pw0000gn/T/pip-req-build-p3_8zncx/iblviewer/qt_application.py", line 6, in <module>
        from ipywebrtc.webrtc import VideoStream
    ModuleNotFoundError: No module named 'ipywebrtc'
    ----------------------------------------
WARNING: Discarding git+https://github.com/int-brain-lab/iblviewer.git. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
(iblenv) mt@Marsas-MacBook-Pro int-brain-lab % 
`

<img width="1032" alt="Screen Shot 2021-08-17 at 10 53 56 AM" src="https://user-images.githubusercontent.com/35471951/129776387-af0575aa-f488-4c72-9279-4772421ee13f.png">

**Comment by nantille** [comment]
A strange error because ipywebrtc should be downloaded by packages that use it (I don't directly import it in my code).  I've added it in the dependencies. Could you try again and tell me if you still have this error? `pip uninstall iblviewer`then `pip install git+https://github.com/int-brain-lab/iblviewer.git`

**Comment by Marsataheri** [comment]
Yes, I'm getting the same error still. Attached is the screenshot.
 
<img width="908" alt="Screen Shot 2021-08-19 at 3 36 47 PM" src="https://user-images.githubusercontent.com/35471951/130153175-bed837e9-d81f-49d6-83c1-b04ca50c9a41.png">

**Comment by nantille** [comment]
Could you try to run `pip install ipywebrtc` (in your iblenv) before installing the viewer? The error says this package is missing so that should solve it hopefully.

**Comment by nantille** [comment]
Nevermind that. There was an error in the setup.py which caused pip to output the error you mentioned. This is fixed so now you may install the viewer properly. I've tested it in a new Python 3.9 environment just to make sure it works. Let me know if you see further issues. Thanks!

**Comment by Marsataheri** [comment]
Thanks! I was able to update iblviewer now.
