### ISSUE TITLE
as_segments option does not work in the ibl_insertion_probes example

### ISSUE THREAD

**Issue by guidomeijer** [int-brain-lab/iblviewer#9]
When I run the example as is everything works fine but when I change as_segments to True I don't see any insertions anymore..

**Comment by guidomeijer** [comment]
After updating this functionality is still not available, maybe you forgot to update the repo?

**Comment by nantille** [comment]
You were right, thanks for spotting this. The commit was dangling for no reason. The repo is updated now.

**Comment by guidomeijer** [comment]
It's working now, thank you so much for this!
